# Server
server.port=8082

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/clinic

spring.datasource.username=root
spring.datasource.password=subham2606

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Formatting SQL
spring.jpa.properties.hibernate.format_sql=true

# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
